"""initial_schema

Revision ID: 47328886ad9f
Revises: 
Create Date: 2026-07-13 18:25:05.552600
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47328886ad9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_encoding', sa.String(length=20), nullable=False),
    sa.Column('played_at', sa.Date(), nullable=False),
    sa.Column('user_side', sa.String(length=5), nullable=False),
    sa.Column('initial_sfen', sa.Text(), nullable=False),
    sa.Column('usi_moves', sa.JSON(), nullable=False),
    sa.Column('move_count', sa.Integer(), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('critical_position_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_games_analysis_status'), 'games', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_games_normalized_hash'), 'games', ['normalized_hash'], unique=True)
    op.create_index('ix_games_user_created_at', 'games', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('sfen_before', sa.Text(), nullable=False),
    sa.Column('sfen_after', sa.Text(), nullable=False),
    sa.Column('evaluation_raw', sa.Integer(), nullable=True),
    sa.Column('evaluation_user', sa.Integer(), nullable=True),
    sa.Column('win_rate_user', sa.Integer(), nullable=True),
    sa.Column('principal_variation', sa.JSON(), nullable=True),
    sa.Column('is_mate', sa.Boolean(), nullable=False),
    sa.Column('engine_name', sa.String(length=100), nullable=False),
    sa.Column('engine_version', sa.String(length=100), nullable=False),
    sa.Column('search_conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'move_number', name='uq_analysis_game_move')
    )
    op.create_index(op.f('ix_analysis_results_game_id'), 'analysis_results', ['game_id'], unique=False)
    op.create_table('comment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('submitted_snapshot', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_explanation_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_index(op.f('ix_comment_submissions_review_status'), 'comment_submissions', ['review_status'], unique=False)
    op.create_index(op.f('ix_comment_submissions_user_id'), 'comment_submissions', ['user_id'], unique=False)
    op.create_table('critical_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('japanese_move', sa.String(length=100), nullable=False),
    sa.Column('evaluation_before', sa.Integer(), nullable=False),
    sa.Column('evaluation_after', sa.Integer(), nullable=False),
    sa.Column('evaluation_delta', sa.Integer(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('extraction_metadata', sa.JSON(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'move_number', name='uq_critical_game_move')
    )
    op.create_index(op.f('ix_critical_positions_game_id'), 'critical_positions', ['game_id'], unique=False)
    op.create_table('comment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('critical_position_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['critical_position_id'], ['critical_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['comment_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'critical_position_id', 'question_number', name='uq_comment_answer_question')
    )
    op.create_index(op.f('ix_comment_answers_critical_position_id'), 'comment_answers', ['critical_position_id'], unique=False)
    op.create_index(op.f('ix_comment_answers_submission_id'), 'comment_answers', ['submission_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('quality_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['comment_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_submission_id'), 'reviews', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_submission_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_comment_answers_submission_id'), table_name='comment_answers')
    op.drop_index(op.f('ix_comment_answers_critical_position_id'), table_name='comment_answers')
    op.drop_table('comment_answers')
    op.drop_index(op.f('ix_critical_positions_game_id'), table_name='critical_positions')
    op.drop_table('critical_positions')
    op.drop_index(op.f('ix_comment_submissions_user_id'), table_name='comment_submissions')
    op.drop_index(op.f('ix_comment_submissions_review_status'), table_name='comment_submissions')
    op.drop_table('comment_submissions')
    op.drop_index(op.f('ix_analysis_results_game_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_index('ix_games_user_created_at', table_name='games')
    op.drop_index(op.f('ix_games_normalized_hash'), table_name='games')
    op.drop_index(op.f('ix_games_analysis_status'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
